/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

"use client";

import useAdmins from "../../hooks/useAdmins";
import GetAdmins from "./GetAdmins";
import CreateAdmins from "./CreateAdmins";
import UpdateAdmins from "./UpdateAdmins";
import DeleteAdmins from "./DeleteAdmins";

export default function Admins() {
  const { admins, fetchAdmins, createAdmin, updateAdmin, deleteAdmin } =
    useAdmins();

  return (
    <div>
      <GetAdmins admins={admins} onFetch={fetchAdmins} />
      <CreateAdmins onCreate={createAdmin} onFetch={fetchAdmins} />
      <UpdateAdmins onUpdate={updateAdmin} onFetch={fetchAdmins} />
      <DeleteAdmins onDelete={deleteAdmin} onFetch={fetchAdmins} />
    </div>
  );
}
