/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

"use client";

import useCategories from "../../hooks/useCategories";
import GetCategories from "./GetCategories";
import CreateCategories from "./CreateCategories";
import UpdateCategories from "./UpdateCategories";
import DeleteCategories from "./DeleteCategories";

export default function Categories() {
  const {
    categories,
    fetchCategories,
    createCategory,
    updateCategory,
    deleteCategory,
  } = useCategories();

  return (
    <div>
      <GetCategories categories={categories} onFetch={fetchCategories} />
      <CreateCategories onCreate={createCategory} onFetch={fetchCategories} />
      <UpdateCategories onUpdate={updateCategory} onFetch={fetchCategories} />
      <DeleteCategories onDelete={deleteCategory} onFetch={fetchCategories} />
    </div>
  );
}
