/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

"use client";

import useContests from "../../hooks/useContests";
import GetContests from "./GetContests";
import CreateContests from "./CreateContests";
import UpdateContests from "./UpdateContests";
import DeleteContests from "./DeleteContests";

export default function Contests() {
  const {
    contests,
    fetchContests,
    createContest,
    updateContest,
    deleteContest,
  } = useContests();

  return (
    <div>
      <GetContests contests={contests} onFetch={fetchContests} />
      <CreateContests onCreate={createContest} onFetch={fetchContests} />
      <UpdateContests onUpdate={updateContest} onFetch={fetchContests} />
      <DeleteContests onDelete={deleteContest} onFetch={fetchContests} />
    </div>
  );
}
