/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

"use client";

import { FormEventHandler, MouseEventHandler, useState } from "react";
import type { Row, InsertContest } from "../../hooks/useContests";

const fields: Array<keyof InsertContest> = [
  "id",
  "name",
  "description",
  "rules_and_guidelines",
  "submission_deadline",
  "category_id",
  "creator_id",
  "start_date",
];

export default function CreateContests({
  onCreate,
  onFetch,
}: {
  onCreate: (newRow: InsertContest) => Promise<Row | undefined>;
  onFetch: () => Promise<void>;
}) {
  const [message, setMessage] = useState<string>();

  const handleSubmit: FormEventHandler = (event) => {
    event.preventDefault();
    const target = event.target as typeof event.target & InsertContest;
    const newRow = fields
      .map((field) => ({ field, value: (target[field] as any)?.value }))
      .reduce(
        (newRow, { field, value }) => {
          if (value.trim() !== "") {
            newRow[field] = value;
          }
          return newRow;
        },
        {} as Record<keyof InsertContest, any>,
      );
    onCreate(newRow)
      .then((task) => {
        if (task) {
          setMessage("row with id " + task.id + " created!");
          onFetch();
        } else {
          setMessage("failed to create row!");
        }
      })
      .catch((error) => {
        if (error.message) {
          setMessage(error.message);
        } else {
          setMessage("failed to create row!");
        }
      });
  };

  const handleClick: MouseEventHandler<HTMLButtonElement> = () => {
    setMessage(undefined);
  };

  if (message) {
    return (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          height: "98px",
          justifyContent: "end",
        }}
      >
        {message}
        <button
          style={{
            background: "#fff",
            color: "#000",
            marginTop: "20px",
            padding: "8px 10px",
            width: "200px",
            borderRadius: "0.375rem",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
          onClick={handleClick}
        >
          Go Back
        </button>
      </div>
    );
  }

  return (
    <div
      style={{
        paddingTop: "20px",
      }}
    >
      <form
        onSubmit={handleSubmit}
        style={{ display: "flex", flexDirection: "column" }}
      >
        <div className="flex items-center">
          <label
            htmlFor="id"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            id*
          </label>
          <label
            htmlFor="id"
            style={{
              flexBasis: "200px",
            }}
          >
            uuid
          </label>
          <input
            type="text"
            id="id"
            style={{
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <div className="flex items-center">
          <label
            htmlFor="name"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            name
          </label>
          <label
            htmlFor="name"
            style={{
              flexBasis: "200px",
            }}
          >
            text
          </label>
          <input
            type="text"
            id="name"
            style={{
              marginTop: "10px",
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <div className="flex items-center">
          <label
            htmlFor="description"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            description
          </label>
          <label
            htmlFor="description"
            style={{
              flexBasis: "200px",
            }}
          >
            text
          </label>
          <input
            type="text"
            id="description"
            style={{
              marginTop: "10px",
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <div className="flex items-center">
          <label
            htmlFor="rules_and_guidelines"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            rules_and_guidelines
          </label>
          <label
            htmlFor="rules_and_guidelines"
            style={{
              flexBasis: "200px",
            }}
          >
            text
          </label>
          <input
            type="text"
            id="rules_and_guidelines"
            style={{
              marginTop: "10px",
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <div className="flex items-center">
          <label
            htmlFor="submission_deadline"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            submission_deadline
          </label>
          <label
            htmlFor="submission_deadline"
            style={{
              flexBasis: "200px",
            }}
          >
            timestamp with time zone
          </label>
          <input
            type="text"
            id="submission_deadline"
            style={{
              marginTop: "10px",
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <div className="flex items-center">
          <label
            htmlFor="category_id"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            category_id
          </label>
          <label
            htmlFor="category_id"
            style={{
              flexBasis: "200px",
            }}
          >
            uuid
          </label>
          <input
            type="text"
            id="category_id"
            style={{
              marginTop: "10px",
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <div className="flex items-center">
          <label
            htmlFor="creator_id"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            creator_id
          </label>
          <label
            htmlFor="creator_id"
            style={{
              flexBasis: "200px",
            }}
          >
            uuid
          </label>
          <input
            type="text"
            id="creator_id"
            style={{
              marginTop: "10px",
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <div className="flex items-center">
          <label
            htmlFor="start_date"
            style={{
              flexBasis: "200px",
              marginRight: "10px",
            }}
          >
            start_date
          </label>
          <label
            htmlFor="start_date"
            style={{
              flexBasis: "200px",
            }}
          >
            timestamp with time zone
          </label>
          <input
            type="text"
            id="start_date"
            style={{
              marginTop: "10px",
              background: "#000",
              color: "#fff",
              border: "1px solid #34383A",
              marginLeft: "10px",
              flex: "1",
              borderRadius: "0.375rem",
              padding: "4px 16px",
            }}
          />
        </div>

        <button
          type="submit"
          style={{
            background: "#fff",
            color: "#000",
            marginTop: "10px",
            padding: "8px 10px",
            width: "200px",
            borderRadius: "0.375rem",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <div style={{ marginRight: "10px" }}>Run POST</div>
          <svg
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            style={{
              height: "20px",
            }}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M5.25 5.653c0-.856.917-1.398 1.667-.986l11.54 6.348a1.125 1.125 0 010 1.971l-11.54 6.347a1.125 1.125 0 01-1.667-.985V5.653z"
            />
          </svg>
        </button>
      </form>
    </div>
  );
}
