/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

"use client";

import useEntries from "../../hooks/useEntries";
import GetEntries from "./GetEntries";
import CreateEntries from "./CreateEntries";
import UpdateEntries from "./UpdateEntries";
import DeleteEntries from "./DeleteEntries";

export default function Entries() {
  const { entries, fetchEntries, createEntry, updateEntry, deleteEntry } =
    useEntries();

  return (
    <div>
      <GetEntries entries={entries} onFetch={fetchEntries} />
      <CreateEntries onCreate={createEntry} onFetch={fetchEntries} />
      <UpdateEntries onUpdate={updateEntry} onFetch={fetchEntries} />
      <DeleteEntries onDelete={deleteEntry} onFetch={fetchEntries} />
    </div>
  );
}
