/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

"use client";

import useNotifications from "../../hooks/useNotifications";
import GetNotifications from "./GetNotifications";
import CreateNotifications from "./CreateNotifications";
import UpdateNotifications from "./UpdateNotifications";
import DeleteNotifications from "./DeleteNotifications";

export default function Notifications() {
  const {
    notifications,
    fetchNotifications,
    createNotification,
    updateNotification,
    deleteNotification,
  } = useNotifications();

  return (
    <div>
      <GetNotifications
        notifications={notifications}
        onFetch={fetchNotifications}
      />
      <CreateNotifications
        onCreate={createNotification}
        onFetch={fetchNotifications}
      />
      <UpdateNotifications
        onUpdate={updateNotification}
        onFetch={fetchNotifications}
      />
      <DeleteNotifications
        onDelete={deleteNotification}
        onFetch={fetchNotifications}
      />
    </div>
  );
}
