/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

"use client";

import useUsers from "../../hooks/useUsers";
import GetUsers from "./GetUsers";
import CreateUsers from "./CreateUsers";
import UpdateUsers from "./UpdateUsers";
import DeleteUsers from "./DeleteUsers";

export default function Users() {
  const { users, fetchUsers, createUser, updateUser, deleteUser } = useUsers();

  return (
    <div>
      <GetUsers users={users} onFetch={fetchUsers} />
      <CreateUsers onCreate={createUser} onFetch={fetchUsers} />
      <UpdateUsers onUpdate={updateUser} onFetch={fetchUsers} />
      <DeleteUsers onDelete={deleteUser} onFetch={fetchUsers} />
    </div>
  );
}
